on:
  push:
    branches:
      - main
jobs:
  build-and-deploy :
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2 
      with:
        persist-credentials: false

    - uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        source: "*"
        target: "/home/ubuntu/react-app/"



  securitytest:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code  
        uses: actions/checkout@v2        

      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: 'test'
          path: '.'
          format: 'HTML'    
          args: >
            --failOnCVSS 7
            --enableRetired
      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
           name: Depcheck report
           path: ${{github.workspace}}/reports

   #   - uses: actions/checkout@v2        
      - name: DevSkim Scan
        uses: microsoft/DevSkim-Action@v1
      - uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: devskim-results.sarif

      - name: Trufflehog Actions Scan
        uses: edplato/trufflehog-actions-scan@master

      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.5.0
        with:
          target: 'http://65.2.71.22:3000'

      - name: nodejsscan scan
        id: njsscan
        uses: ajinabraham/njsscan-action@master
        with:
          args: '. --sarif --output results.sarif || true'
      
      - name: Upload njsscan report
        uses : actions/upload-artifact@v2
        with :
          path : results.sarif

