on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2 
      with:
        persist-credentials: false

    - name: Install and Build
      run: |
        npm install
        npm run-script build

  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Install SSH Key
      uses : shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }} 
        known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
    - name: Adding Known Hosts
      run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
    - name: Deploy with rsync
      run: rsync -azv . ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/
    - name : Run app
      run: |
        npm install
        npm run-script build
